apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: node
    sync:
      infer:
      - 'src/**/*.js'
  - image: gcr.io/k8s-skaffold/python-reload
    context: python
    sync:
      infer:
      - 'src/**/*.py'
